# Generated by Django 3.2.9 on 2022-01-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Anonymous', max_length=500, verbose_name='ファイル名'),
            preserve_default=False,
        ),
    ]
